apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tool-node.fullname" . }}-ssh-config
  labels:
    app: {{ include "tool-node.name" . }}
data:
  authorized_keys: |
    {{ .Values.sshAuthorizedKeys | nindent 4 }}
