apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "tool-node.fullname" . }}
  labels:
    app: {{ include "tool-node.name" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "tool-node.name" . }}
  podMetricsEndpoints:
    - port: metrics
      path: /debug/metrics/prometheus
      interval: 30s
      scheme: http
      targetPort: 6060
