apiVersion: v1
kind: Service
metadata:
  name: {{ include "tool-node.fullname" . }}-ssh
spec:
  type: NodePort
  selector:
    app: {{ include "tool-node.name" . }}
  ports:
    - name: ssh
      port: 22
      targetPort: 22
      nodePort: {{ .Values.sshNodePort | default 32222 }}
