// Code generated by rlpgen. DO NOT EDIT.

package types

import "github.com/ethereum/go-ethereum/common"
import "github.com/ethereum/go-ethereum/rlp"
import "io"

func (obj *SubSlot) EncodeRLP(_w io.Writer) error {
	w := rlp.NewEncoderBuffer(_w)
	_tmp0 := w.List()
	_tmp1 := w.List()
	for _, _tmp2 := range obj.Txs {
		w.WriteBytes(_tmp2[:])
	}
	w.ListEnd(_tmp1)
	w.WriteUint64(obj.Block)
	w.WriteBytes(obj.BlockParent[:])
	w.WriteUint64(obj.BlockTime)
	w.WriteUint64(uint64(obj.Index))
	w.ListEnd(_tmp0)
	return w.Flush()
}

func (obj *SubSlot) DecodeRLP(dec *rlp.Stream) error {
	var _tmp0 SubSlot
	{
		if _, err := dec.List(); err != nil {
			return err
		}
		// Txs:
		var _tmp1 []common.Hash
		if _, err := dec.List(); err != nil {
			return err
		}
		for dec.MoreDataInList() {
			var _tmp2 common.Hash
			if err := dec.ReadBytes(_tmp2[:]); err != nil {
				return err
			}
			_tmp1 = append(_tmp1, _tmp2)
		}
		if err := dec.ListEnd(); err != nil {
			return err
		}
		_tmp0.Txs = _tmp1
		// Block:
		_tmp3, err := dec.Uint64()
		if err != nil {
			return err
		}
		_tmp0.Block = _tmp3
		// BlockParent:
		var _tmp4 common.Hash
		if err := dec.ReadBytes(_tmp4[:]); err != nil {
			return err
		}
		_tmp0.BlockParent = _tmp4
		// BlockTime:
		_tmp5, err := dec.Uint64()
		if err != nil {
			return err
		}
		_tmp0.BlockTime = _tmp5
		// Index:
		_tmp6, err := dec.Uint8()
		if err != nil {
			return err
		}
		_tmp0.Index = _tmp6
		if err := dec.ListEnd(); err != nil {
			return err
		}
	}
	*obj = _tmp0
	return nil
}
