// Code generated by rlpgen. DO NOT EDIT.

package types

import "github.com/ethereum/go-ethereum/common"
import "github.com/ethereum/go-ethereum/rlp"
import "github.com/holiman/uint256"
import "io"

func (obj *Commitment) EncodeRLP(_w io.Writer) error {
	w := rlp.NewEncoderBuffer(_w)
	_tmp0 := w.List()
	_tmp1 := w.List()
	for _, _tmp2 := range obj.Txs {
		w.WriteBytes(_tmp2[:])
	}
	w.ListEnd(_tmp1)
	w.WriteUint64(obj.Block)
	w.WriteUint64(obj.BlockTime)
	w.WriteBytes(obj.BlockParent[:])
	w.WriteUint64(uint64(obj.SubSlot))
	w.WriteUint64(uint64(obj.ExpiresAtSubSlot))
	if obj.Fees == nil {
		w.Write(rlp.EmptyString)
	} else {
		w.WriteUint256(obj.Fees)
	}
	w.WriteUint64(obj.TxsSize)
	w.WriteUint64(obj.GasUsed)
	w.WriteUint64(obj.MaxGasLimit)
	_tmp3 := w.List()
	for _, _tmp4 := range obj.Accesses {
		_tmp5 := w.List()
		w.WriteBytes(_tmp4.Address[:])
		w.WriteUint64(uint64(_tmp4.Meta))
		_tmp6 := len(_tmp4.Storage) > 0
		if _tmp6 {
			_tmp7 := w.List()
			for _, _tmp8 := range _tmp4.Storage {
				_tmp9 := w.List()
				w.WriteBytes(_tmp8.Slot[:])
				w.WriteUint64(uint64(_tmp8.Ops))
				w.ListEnd(_tmp9)
			}
			w.ListEnd(_tmp7)
		}
		w.ListEnd(_tmp5)
	}
	w.ListEnd(_tmp3)
	_tmp10 := obj.StateDiff != nil
	_tmp11 := len(obj.Logs) > 0
	_tmp12 := len(obj.NewTxs) > 0
	if _tmp10 || _tmp11 || _tmp12 {
		if err := obj.StateDiff.EncodeRLP(w); err != nil {
			return err
		}
	}
	if _tmp11 || _tmp12 {
		_tmp13 := w.List()
		for _, _tmp14 := range obj.Logs {
			if err := _tmp14.EncodeRLP(w); err != nil {
				return err
			}
		}
		w.ListEnd(_tmp13)
	}
	if _tmp12 {
		_tmp15 := w.List()
		for _, _tmp16 := range obj.NewTxs {
			if err := _tmp16.EncodeRLP(w); err != nil {
				return err
			}
		}
		w.ListEnd(_tmp15)
	}
	w.ListEnd(_tmp0)
	return w.Flush()
}

func (obj *Commitment) DecodeRLP(dec *rlp.Stream) error {
	var _tmp0 Commitment
	{
		if _, err := dec.List(); err != nil {
			return err
		}
		// Txs:
		var _tmp1 []common.Hash
		if _, err := dec.List(); err != nil {
			return err
		}
		for dec.MoreDataInList() {
			var _tmp2 common.Hash
			if err := dec.ReadBytes(_tmp2[:]); err != nil {
				return err
			}
			_tmp1 = append(_tmp1, _tmp2)
		}
		if err := dec.ListEnd(); err != nil {
			return err
		}
		_tmp0.Txs = _tmp1
		// Block:
		_tmp3, err := dec.Uint64()
		if err != nil {
			return err
		}
		_tmp0.Block = _tmp3
		// BlockTime:
		_tmp4, err := dec.Uint64()
		if err != nil {
			return err
		}
		_tmp0.BlockTime = _tmp4
		// BlockParent:
		var _tmp5 common.Hash
		if err := dec.ReadBytes(_tmp5[:]); err != nil {
			return err
		}
		_tmp0.BlockParent = _tmp5
		// SubSlot:
		_tmp6, err := dec.Uint8()
		if err != nil {
			return err
		}
		_tmp0.SubSlot = _tmp6
		// ExpiresAtSubSlot:
		_tmp7, err := dec.Uint8()
		if err != nil {
			return err
		}
		_tmp0.ExpiresAtSubSlot = _tmp7
		// Fees:
		var _tmp8 uint256.Int
		if err := dec.ReadUint256(&_tmp8); err != nil {
			return err
		}
		_tmp0.Fees = &_tmp8
		// TxsSize:
		_tmp9, err := dec.Uint64()
		if err != nil {
			return err
		}
		_tmp0.TxsSize = _tmp9
		// GasUsed:
		_tmp10, err := dec.Uint64()
		if err != nil {
			return err
		}
		_tmp0.GasUsed = _tmp10
		// MaxGasLimit:
		_tmp11, err := dec.Uint64()
		if err != nil {
			return err
		}
		_tmp0.MaxGasLimit = _tmp11
		// Accesses:
		var _tmp12 []Access
		if _, err := dec.List(); err != nil {
			return err
		}
		for dec.MoreDataInList() {
			var _tmp13 Access
			{
				if _, err := dec.List(); err != nil {
					return err
				}
				// Address:
				var _tmp14 common.Address
				if err := dec.ReadBytes(_tmp14[:]); err != nil {
					return err
				}
				_tmp13.Address = _tmp14
				// Meta:
				_tmp15, err := dec.Uint8()
				if err != nil {
					return err
				}
				_tmp13.Meta = _tmp15
				// Storage:
				if dec.MoreDataInList() {
					var _tmp16 []SlotOp
					if _, err := dec.List(); err != nil {
						return err
					}
					for dec.MoreDataInList() {
						var _tmp17 SlotOp
						{
							if _, err := dec.List(); err != nil {
								return err
							}
							// Slot:
							var _tmp18 common.Hash
							if err := dec.ReadBytes(_tmp18[:]); err != nil {
								return err
							}
							_tmp17.Slot = _tmp18
							// Ops:
							_tmp19, err := dec.Uint8()
							if err != nil {
								return err
							}
							_tmp17.Ops = _tmp19
							if err := dec.ListEnd(); err != nil {
								return err
							}
						}
						_tmp16 = append(_tmp16, _tmp17)
					}
					if err := dec.ListEnd(); err != nil {
						return err
					}
					_tmp13.Storage = _tmp16
				}
				if err := dec.ListEnd(); err != nil {
					return err
				}
			}
			_tmp12 = append(_tmp12, _tmp13)
		}
		if err := dec.ListEnd(); err != nil {
			return err
		}
		_tmp0.Accesses = _tmp12
		// StateDiff:
		if dec.MoreDataInList() {
			_tmp20 := new(StateDiff)
			if err := _tmp20.DecodeRLP(dec); err != nil {
				return err
			}
			_tmp0.StateDiff = _tmp20
			// Logs:
			if dec.MoreDataInList() {
				var _tmp21 []*Log
				if _, err := dec.List(); err != nil {
					return err
				}
				for dec.MoreDataInList() {
					_tmp22 := new(Log)
					if err := _tmp22.DecodeRLP(dec); err != nil {
						return err
					}
					_tmp21 = append(_tmp21, _tmp22)
				}
				if err := dec.ListEnd(); err != nil {
					return err
				}
				_tmp0.Logs = _tmp21
				// NewTxs:
				if dec.MoreDataInList() {
					var _tmp23 []*Transaction
					if _, err := dec.List(); err != nil {
						return err
					}
					for dec.MoreDataInList() {
						_tmp24 := new(Transaction)
						if err := _tmp24.DecodeRLP(dec); err != nil {
							return err
						}
						_tmp23 = append(_tmp23, _tmp24)
					}
					if err := dec.ListEnd(); err != nil {
						return err
					}
					_tmp0.NewTxs = _tmp23
				}
			}
		}
		if err := dec.ListEnd(); err != nil {
			return err
		}
	}
	*obj = _tmp0
	return nil
}
