// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package types

import (
	"encoding/json"

	"github.com/ethereum/go-ethereum/common"
)

var _ = (*toolIDMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (s SubSlot) MarshalJSON() ([]byte, error) {
	type SubSlot struct {
		Txs         []common.Hash `json:"txs"`
		Block       uint64        `json:"block"`
		BlockParent common.Hash   `json:"blockParent"`
		BlockTime   uint64        `json:"blockTime"`
		Index       uint8         `json:"index"`
		GasUsed     uint64        `json:"gasUsed" rlp:"-"`
		Accesses    Accesses      `json:"-" rlp:"-"`
		StateDiff   *StateDiff    `json:"stateDiff" rlp:"-"`
		Receipts    Receipts      `json:"receipts" rlp:"-"`
		ID          common.Hash   `json:"ID"`
	}
	var enc SubSlot
	enc.Txs = s.Txs
	enc.Block = s.Block
	enc.BlockParent = s.BlockParent
	enc.BlockTime = s.BlockTime
	enc.Index = s.Index
	enc.GasUsed = s.GasUsed
	enc.Accesses = s.Accesses
	enc.StateDiff = s.StateDiff
	enc.Receipts = s.Receipts
	enc.ID = s.ID()
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (s *SubSlot) UnmarshalJSON(input []byte) error {
	type SubSlot struct {
		Txs         []common.Hash `json:"txs"`
		Block       *uint64       `json:"block"`
		BlockParent *common.Hash  `json:"blockParent"`
		BlockTime   *uint64       `json:"blockTime"`
		Index       *uint8        `json:"index"`
		GasUsed     *uint64       `json:"gasUsed" rlp:"-"`
		Accesses    *Accesses     `json:"-" rlp:"-"`
		StateDiff   *StateDiff    `json:"stateDiff" rlp:"-"`
		Receipts    *Receipts     `json:"receipts" rlp:"-"`
	}
	var dec SubSlot
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.Txs != nil {
		s.Txs = dec.Txs
	}
	if dec.Block != nil {
		s.Block = *dec.Block
	}
	if dec.BlockParent != nil {
		s.BlockParent = *dec.BlockParent
	}
	if dec.BlockTime != nil {
		s.BlockTime = *dec.BlockTime
	}
	if dec.Index != nil {
		s.Index = *dec.Index
	}
	if dec.GasUsed != nil {
		s.GasUsed = *dec.GasUsed
	}
	if dec.Accesses != nil {
		s.Accesses = *dec.Accesses
	}
	if dec.StateDiff != nil {
		s.StateDiff = dec.StateDiff
	}
	if dec.Receipts != nil {
		s.Receipts = *dec.Receipts
	}
	return nil
}
