// Code generated by rlpgen. DO NOT EDIT.

package types

import "github.com/ethereum/go-ethereum/common"
import "github.com/ethereum/go-ethereum/rlp"
import "io"

func (obj *KeyValue) EncodeRLP(_w io.Writer) error {
	w := rlp.NewEncoderBuffer(_w)
	_tmp0 := w.List()
	w.WriteBytes(obj.Key[:])
	w.WriteBytes(obj.Value[:])
	w.ListEnd(_tmp0)
	return w.Flush()
}

func (obj *KeyValue) DecodeRLP(dec *rlp.Stream) error {
	var _tmp0 KeyValue
	{
		if _, err := dec.List(); err != nil {
			return err
		}
		// Key:
		var _tmp1 common.Hash
		if err := dec.ReadBytes(_tmp1[:]); err != nil {
			return err
		}
		_tmp0.Key = _tmp1
		// Value:
		var _tmp2 common.Hash
		if err := dec.ReadBytes(_tmp2[:]); err != nil {
			return err
		}
		_tmp0.Value = _tmp2
		if err := dec.ListEnd(); err != nil {
			return err
		}
	}
	*obj = _tmp0
	return nil
}
