// Code generated by rlpgen. DO NOT EDIT.

package types

import "github.com/ethereum/go-ethereum/common"
import "github.com/ethereum/go-ethereum/rlp"
import "github.com/holiman/uint256"
import "io"

func (obj *AccountChange) EncodeRLP(_w io.Writer) error {
	w := rlp.NewEncoderBuffer(_w)
	_tmp0 := w.List()
	w.WriteBytes(obj.Address[:])
	if obj.BalanceInc == nil {
		w.Write(rlp.EmptyString)
	} else {
		w.WriteUint256(obj.BalanceInc)
	}
	_tmp1 := obj.BalanceDec != nil
	_tmp2 := len(obj.Storage) > 0
	_tmp3 := obj.NewNonce != 0
	_tmp4 := len(obj.NewCode) > 0
	if _tmp1 || _tmp2 || _tmp3 || _tmp4 {
		if obj.BalanceDec == nil {
			w.Write(rlp.EmptyString)
		} else {
			w.WriteUint256(obj.BalanceDec)
		}
	}
	if _tmp2 || _tmp3 || _tmp4 {
		_tmp5 := w.List()
		for _, _tmp6 := range obj.Storage {
			if err := _tmp6.EncodeRLP(w); err != nil {
				return err
			}
		}
		w.ListEnd(_tmp5)
	}
	if _tmp3 || _tmp4 {
		w.WriteUint64(obj.NewNonce)
	}
	if _tmp4 {
		w.WriteBytes(obj.NewCode)
	}
	w.ListEnd(_tmp0)
	return w.Flush()
}

func (obj *AccountChange) DecodeRLP(dec *rlp.Stream) error {
	var _tmp0 AccountChange
	{
		if _, err := dec.List(); err != nil {
			return err
		}
		// Address:
		var _tmp1 common.Address
		if err := dec.ReadBytes(_tmp1[:]); err != nil {
			return err
		}
		_tmp0.Address = _tmp1
		// BalanceInc:
		var _tmp2 uint256.Int
		if err := dec.ReadUint256(&_tmp2); err != nil {
			return err
		}
		_tmp0.BalanceInc = &_tmp2
		// BalanceDec:
		if dec.MoreDataInList() {
			var _tmp3 uint256.Int
			if err := dec.ReadUint256(&_tmp3); err != nil {
				return err
			}
			_tmp0.BalanceDec = &_tmp3
			// Storage:
			if dec.MoreDataInList() {
				var _tmp4 []*KeyValue
				if _, err := dec.List(); err != nil {
					return err
				}
				for dec.MoreDataInList() {
					_tmp5 := new(KeyValue)
					if err := _tmp5.DecodeRLP(dec); err != nil {
						return err
					}
					_tmp4 = append(_tmp4, _tmp5)
				}
				if err := dec.ListEnd(); err != nil {
					return err
				}
				_tmp0.Storage = _tmp4
				// NewNonce:
				if dec.MoreDataInList() {
					_tmp6, err := dec.Uint64()
					if err != nil {
						return err
					}
					_tmp0.NewNonce = _tmp6
					// NewCode:
					if dec.MoreDataInList() {
						_tmp7, err := dec.Bytes()
						if err != nil {
							return err
						}
						_tmp0.NewCode = _tmp7
					}
				}
			}
		}
		if err := dec.ListEnd(); err != nil {
			return err
		}
	}
	*obj = _tmp0
	return nil
}
