// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package types

import (
	"encoding/json"

	"github.com/ethereum/go-ethereum/common"
	"github.com/holiman/uint256"
)

var _ = (*toolIDMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (c Commitment) MarshalJSON() ([]byte, error) {
	type Commitment struct {
		Txs              []common.Hash `json:"-"`
		Block            uint64        `json:"block"`
		BlockTime        uint64        `json:"blockTime"`
		BlockParent      common.Hash   `json:"blockParent"`
		SubSlot          uint8         `json:"subSlot"`
		ExpiresAtSubSlot uint8         `json:"expires"`
		Fees             *uint256.Int  `json:"fees"`
		TxsSize          uint64        `json:"txsSize"`
		GasUsed          uint64        `json:"gasUsed"`
		MaxGasLimit      uint64        `json:"maxGasLimit"`
		Accesses         Accesses      `json:"accesses"`
		StateDiff        *StateDiff    `json:"stateDiff" rlp:"optional"`
		Logs             []*Log        `json:"logs,omitempty" rlp:"optional"`
		NewTxs           Transactions  `json:"-" rlp:"optional"`
		ID               common.Hash   `json:"ID"`
	}
	var enc Commitment
	enc.Txs = c.Txs
	enc.Block = c.Block
	enc.BlockTime = c.BlockTime
	enc.BlockParent = c.BlockParent
	enc.SubSlot = c.SubSlot
	enc.ExpiresAtSubSlot = c.ExpiresAtSubSlot
	enc.Fees = c.Fees
	enc.TxsSize = c.TxsSize
	enc.GasUsed = c.GasUsed
	enc.MaxGasLimit = c.MaxGasLimit
	enc.Accesses = c.Accesses
	enc.StateDiff = c.StateDiff
	enc.Logs = c.Logs
	enc.NewTxs = c.NewTxs
	enc.ID = c.ID()
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (c *Commitment) UnmarshalJSON(input []byte) error {
	type Commitment struct {
		Txs              []common.Hash `json:"-"`
		Block            *uint64       `json:"block"`
		BlockTime        *uint64       `json:"blockTime"`
		BlockParent      *common.Hash  `json:"blockParent"`
		SubSlot          *uint8        `json:"subSlot"`
		ExpiresAtSubSlot *uint8        `json:"expires"`
		Fees             *uint256.Int  `json:"fees"`
		TxsSize          *uint64       `json:"txsSize"`
		GasUsed          *uint64       `json:"gasUsed"`
		MaxGasLimit      *uint64       `json:"maxGasLimit"`
		Accesses         *Accesses     `json:"accesses"`
		StateDiff        *StateDiff    `json:"stateDiff" rlp:"optional"`
		Logs             []*Log        `json:"logs,omitempty" rlp:"optional"`
		NewTxs           *Transactions `json:"-" rlp:"optional"`
	}
	var dec Commitment
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.Txs != nil {
		c.Txs = dec.Txs
	}
	if dec.Block != nil {
		c.Block = *dec.Block
	}
	if dec.BlockTime != nil {
		c.BlockTime = *dec.BlockTime
	}
	if dec.BlockParent != nil {
		c.BlockParent = *dec.BlockParent
	}
	if dec.SubSlot != nil {
		c.SubSlot = *dec.SubSlot
	}
	if dec.ExpiresAtSubSlot != nil {
		c.ExpiresAtSubSlot = *dec.ExpiresAtSubSlot
	}
	if dec.Fees != nil {
		c.Fees = dec.Fees
	}
	if dec.TxsSize != nil {
		c.TxsSize = *dec.TxsSize
	}
	if dec.GasUsed != nil {
		c.GasUsed = *dec.GasUsed
	}
	if dec.MaxGasLimit != nil {
		c.MaxGasLimit = *dec.MaxGasLimit
	}
	if dec.Accesses != nil {
		c.Accesses = *dec.Accesses
	}
	if dec.StateDiff != nil {
		c.StateDiff = dec.StateDiff
	}
	if dec.Logs != nil {
		c.Logs = dec.Logs
	}
	if dec.NewTxs != nil {
		c.NewTxs = *dec.NewTxs
	}
	return nil
}
