// Code generated by rlpgen. DO NOT EDIT.

package types

import "github.com/ethereum/go-ethereum/common"
import "github.com/ethereum/go-ethereum/rlp"
import "io"

func (obj *SlotOp) EncodeRLP(_w io.Writer) error {
	w := rlp.NewEncoderBuffer(_w)
	_tmp0 := w.List()
	w.WriteBytes(obj.Slot[:])
	w.WriteUint64(uint64(obj.Ops))
	w.ListEnd(_tmp0)
	return w.Flush()
}

func (obj *SlotOp) DecodeRLP(dec *rlp.Stream) error {
	var _tmp0 SlotOp
	{
		if _, err := dec.List(); err != nil {
			return err
		}
		// Slot:
		var _tmp1 common.Hash
		if err := dec.ReadBytes(_tmp1[:]); err != nil {
			return err
		}
		_tmp0.Slot = _tmp1
		// Ops:
		_tmp2, err := dec.Uint8()
		if err != nil {
			return err
		}
		_tmp0.Ops = _tmp2
		if err := dec.ListEnd(); err != nil {
			return err
		}
	}
	*obj = _tmp0
	return nil
}
