// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package types

import (
	"encoding/json"

	"github.com/ethereum/go-ethereum/common"
)

var _ = (*metaMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (a Access) MarshalJSON() ([]byte, error) {
	type Access struct {
		Address common.Address `json:"-"`
		Meta    uint8          `json:"-"`
		Storage StorageOps     `json:"storage,omitempty" rlp:"optional"`
		Balance uint8          `json:"balance,omitempty"`
		Nonce   uint8          `json:"nonce,omitempty"`
		Code    uint8          `json:"code,omitempty"`
	}
	var enc Access
	enc.Address = a.Address
	enc.Meta = a.Meta
	enc.Storage = a.Storage
	enc.Balance = a.Balance()
	enc.Nonce = a.Nonce()
	enc.Code = a.Code()
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (a *Access) UnmarshalJSON(input []byte) error {
	type Access struct {
		Address *common.Address `json:"-"`
		Meta    *uint8          `json:"-"`
		Storage *StorageOps     `json:"storage,omitempty" rlp:"optional"`
	}
	var dec Access
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.Address != nil {
		a.Address = *dec.Address
	}
	if dec.Meta != nil {
		a.Meta = *dec.Meta
	}
	if dec.Storage != nil {
		a.Storage = *dec.Storage
	}
	return nil
}
