// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package types

import (
	"encoding/json"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/common/hexutil"
	"github.com/holiman/uint256"
)

var _ = (*accountChangeMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (a AccountChange) MarshalJSON() ([]byte, error) {
	type AccountChange struct {
		Address    common.Address `json:"-"`
		BalanceInc *uint256.Int   `json:"-"`
		BalanceDec *uint256.Int   `json:"-" rlp:"optional"`
		Storage    StorageValues  `json:"storage,omitempty" rlp:"optional"`
		NewNonce   uint64         `json:"nonce,omitempty" rlp:"optional"`
		NewCode    hexutil.Bytes  `json:"code,omitempty" rlp:"optional"`
		Balance    string         `json:"balance,omitempty"`
	}
	var enc AccountChange
	enc.Address = a.Address
	enc.BalanceInc = a.BalanceInc
	enc.BalanceDec = a.BalanceDec
	enc.Storage = a.Storage
	enc.NewNonce = a.NewNonce
	enc.NewCode = a.NewCode
	enc.Balance = a.Balance()
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (a *AccountChange) UnmarshalJSON(input []byte) error {
	type AccountChange struct {
		Address    *common.Address `json:"-"`
		BalanceInc *uint256.Int    `json:"-"`
		BalanceDec *uint256.Int    `json:"-" rlp:"optional"`
		Storage    *StorageValues  `json:"storage,omitempty" rlp:"optional"`
		NewNonce   *uint64         `json:"nonce,omitempty" rlp:"optional"`
		NewCode    *hexutil.Bytes  `json:"code,omitempty" rlp:"optional"`
	}
	var dec AccountChange
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.Address != nil {
		a.Address = *dec.Address
	}
	if dec.BalanceInc != nil {
		a.BalanceInc = dec.BalanceInc
	}
	if dec.BalanceDec != nil {
		a.BalanceDec = dec.BalanceDec
	}
	if dec.Storage != nil {
		a.Storage = *dec.Storage
	}
	if dec.NewNonce != nil {
		a.NewNonce = *dec.NewNonce
	}
	if dec.NewCode != nil {
		a.NewCode = *dec.NewCode
	}
	return nil
}
