// Code generated by rlpgen. DO NOT EDIT.

package types

import "github.com/ethereum/go-ethereum/common"
import "github.com/ethereum/go-ethereum/rlp"
import "io"

func (obj *Access) EncodeRLP(_w io.Writer) error {
	w := rlp.NewEncoderBuffer(_w)
	_tmp0 := w.List()
	w.WriteBytes(obj.Address[:])
	w.WriteUint64(uint64(obj.Meta))
	_tmp1 := len(obj.Storage) > 0
	if _tmp1 {
		_tmp2 := w.List()
		for _, _tmp3 := range obj.Storage {
			_tmp4 := w.List()
			w.WriteBytes(_tmp3.Slot[:])
			w.WriteUint64(uint64(_tmp3.Ops))
			w.ListEnd(_tmp4)
		}
		w.ListEnd(_tmp2)
	}
	w.ListEnd(_tmp0)
	return w.Flush()
}

func (obj *Access) DecodeRLP(dec *rlp.Stream) error {
	var _tmp0 Access
	{
		if _, err := dec.List(); err != nil {
			return err
		}
		// Address:
		var _tmp1 common.Address
		if err := dec.ReadBytes(_tmp1[:]); err != nil {
			return err
		}
		_tmp0.Address = _tmp1
		// Meta:
		_tmp2, err := dec.Uint8()
		if err != nil {
			return err
		}
		_tmp0.Meta = _tmp2
		// Storage:
		if dec.MoreDataInList() {
			var _tmp3 []SlotOp
			if _, err := dec.List(); err != nil {
				return err
			}
			for dec.MoreDataInList() {
				var _tmp4 SlotOp
				{
					if _, err := dec.List(); err != nil {
						return err
					}
					// Slot:
					var _tmp5 common.Hash
					if err := dec.ReadBytes(_tmp5[:]); err != nil {
						return err
					}
					_tmp4.Slot = _tmp5
					// Ops:
					_tmp6, err := dec.Uint8()
					if err != nil {
						return err
					}
					_tmp4.Ops = _tmp6
					if err := dec.ListEnd(); err != nil {
						return err
					}
				}
				_tmp3 = append(_tmp3, _tmp4)
			}
			if err := dec.ListEnd(); err != nil {
				return err
			}
			_tmp0.Storage = _tmp3
		}
		if err := dec.ListEnd(); err != nil {
			return err
		}
	}
	*obj = _tmp0
	return nil
}
