package types

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"math/big"
	"slices"
	"sort"
	"strings"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/common/hexutil"
	"github.com/holiman/uint256"
)

//go:generate go run ../../rlp/rlpgen -type KeyValue -decoder=true -out gen_key_value_rlp.go
//go:generate go run ../../rlp/rlpgen -type StateDiff -decoder=true -out gen_state_diff_rlp.go
//go:generate go run ../../rlp/rlpgen -type AccountChange -decoder=true -out gen_account_change_rlp.go
//go:generate go run github.com/fjl/gencodec -type AccountChange -field-override accountChangeMarshaling -out gen_account_change_json.go

// StateDiff represents the state changes between two points in Ethereum state.
// It's typically generated by comparing account states before and after transaction execution,
// leveraging the txsSnapshotStack to track original account values.
//
// StateDiff serves several critical functions in Ethereum:
// 1. Enables state synchronization without full transaction re-execution
// 2. Supports lightweight clients by transmitting minimal state updates
// 3. Facilitates debugging and transaction analysis tools
// 4. Provides a basis for transaction fee calculations in some contexts
//
// StateDiff can be serialized, transmitted, and later applied to replicate
// state transitions without re-executing the underlying transactions.
type StateDiff struct {
	Changes AccountChanges `json:"changes"` // Accounts that were modified during execution
}

type AccountChanges []*AccountChange

func (aa AccountChanges) MarshalJSON() ([]byte, error) {
	length := len(aa)
	if length == 0 {
		return nil, nil
	}

	data := make(map[common.Address]*AccountChange, length)
	for _, value := range aa {
		data[value.Address] = value
	}
	return json.Marshal(data)
}

// IsEmpty checks whether a StateDiff contains any changes.
// Returns true if the StateDiff is nil or has no updates and no removals.
func (sd *StateDiff) IsEmpty() bool {
	return sd == nil || len(sd.Changes) == 0
}

type StorageValues []*KeyValue

func (s StorageValues) MarshalJSON() ([]byte, error) {
	length := len(s)
	if length == 0 {
		return nil, nil
	}

	data := make(map[common.Hash]common.Hash, length)
	for _, kv := range s {
		data[kv.Key] = kv.Value
	}
	return json.Marshal(data)
}

// KeyValue represents a key-value pair for account storage slots.
type KeyValue struct {
	Key   common.Hash `json:"key"`   // Storage slot hash
	Value common.Hash `json:"value"` // Current value at that slot
}

// AccountChange represents changes to an Ethereum account.
// It tracks precise changes between the original account state (pre-execution)
// and its final state (post-execution).
//
// Balance changes are tracked separately as increases/decreases rather than net value.
// This provides more granular information about the nature of balance changes and
// helps with merging StateDiffs from different sources.
type AccountChange struct {
	Address    common.Address `json:"-"`                                // The account's address
	BalanceInc *uint256.Int   `json:"-"`                                // Amount by which balance increased (if any)
	BalanceDec *uint256.Int   `json:"-" rlp:"optional"`                 // Amount by which balance decreased (if any)
	Storage    StorageValues  `json:"storage,omitempty" rlp:"optional"` // State storage slot updates
	NewNonce   uint64         `json:"nonce,omitempty" rlp:"optional"`   // New account nonce (if changed)
	NewCode    []byte         `json:"code,omitempty" rlp:"optional"`    // New contract code or zero delegation addr
}

// accountUpdateMarshaling provides custom marshaling rules for AccountChange
type accountChangeMarshaling struct {
	Balance string `json:"balance,omitempty"` // adds call to Balance() in MarshalJSON
	NewCode hexutil.Bytes
}

// Balance returns a string representation of the account's balance change.
// Returns an empty string if there's no balance change.
func (s *AccountChange) Balance() string {
	if balanceDiff := s.BalanceDiff(); balanceDiff.Sign() != 0 {
		return balanceDiff.String()
	}
	return ""
}

// BalanceDiff calculates the net balance change by subtracting any balance
// decrease from any balance increase. Returns a big.Int representing the
// resulting difference.
func (s *AccountChange) BalanceDiff() *big.Int {
	balanceDiff := new(big.Int)
	if s.BalanceInc != nil {
		balanceDiff.Add(balanceDiff, s.BalanceInc.ToBig())
	}
	if s.BalanceDec != nil {
		balanceDiff.Sub(balanceDiff, s.BalanceDec.ToBig())
	}
	return balanceDiff
}

// String returns a human-readable representation of the StateDiff.
// The output is sorted by address and includes all account updates
// and removals for better readability and deterministic output.
func (sd *StateDiff) String() string {
	if sd.IsEmpty() {
		return ""
	}

	var sb strings.Builder

	sort.Slice(sd.Changes, func(i, j int) bool {
		return bytes.Compare(sd.Changes[i].Address[:], sd.Changes[j].Address[:]) < 0
	})

	sb.WriteString("Changes:\n")
	for _, account := range sd.Changes {
		sb.WriteString(fmt.Sprintf("Address: %s\n", account.Address))
		sb.WriteString(fmt.Sprintf("\tbalance: %s\n", account.BalanceDiff()))
		sb.WriteString(fmt.Sprintf("\tnonce: %d\n", account.NewNonce))
		sb.WriteString(fmt.Sprintf("\tcode: %x\n", account.NewCode))

		sort.Slice(account.Storage, func(i, j int) bool {
			return bytes.Compare(account.Storage[i].Key[:], account.Storage[j].Key[:]) < 0
		})
		for _, kv := range account.Storage {
			sb.WriteString(fmt.Sprintf("\t\tslot: %x, value: %x\n",
				kv.Key, kv.Value))
		}
	}

	return sb.String()
}

// Common error types that can occur during state diff operations
var (
	errAccountBalanceOverflow = errors.New("account balance overflow")
	errAccountStateUpdate     = errors.New("account state update")
	errStorageSlotUpdate      = errors.New("storage slot update")
)

// MergeError represents a conflict that occurred during StateDiff merging.
// It contains information about the conflicting address, storage slot (if applicable),
// and the indices of the conflicting diffs.
type MergeError struct {
	addr      common.Address // Address where conflict occurred
	slot      *common.Hash   // Optional storage slot (if conflict is storage-related)
	conflicts [2]int         // Indices of the conflicting diffs
	error     error          // The underlying error
}

// NewMergeError creates a new MergeError with the given parameters.
func NewMergeError(addr common.Address, slot *common.Hash, conflict1, conflict2 int, error error) *MergeError {
	return &MergeError{addr: addr, slot: slot, conflicts: [2]int{conflict1, conflict2}, error: error}
}

// Addr returns the address and optional storage slot where the merge conflict occurred.
func (m *MergeError) Addr() (common.Address, *common.Hash) {
	return m.addr, m.slot
}

// Conflicts returns the indices of the conflicting StateDiffs.
func (m *MergeError) Conflicts() (int, int) {
	return m.conflicts[0], m.conflicts[1]
}

// Error implements the error interface and returns a human-readable
// error message including the conflicting address and slot if applicable.
func (m *MergeError) Error() string {
	if m.slot != nil {
		return fmt.Sprintf("%s: addr %s slot %s", m.error, m.addr, m.slot)
	}
	return fmt.Sprintf("%s: addr %s", m.error, m.addr)
}

// Unwrap returns the underlying error for compatibility with errors.Is/As.
func (m *MergeError) Unwrap() error {
	return m.error
}

// MergeStateDiffs merges multiple StateDiffs objects that don't have conflicts.
// This function implements a careful conflict detection algorithm to ensure
// that the resulting merged diff is consistent and can be safely applied.
//
// Conflict cases include:
// 1. An account's nonce or code is updated in multiple diffs
// 2. The same storage slot is modified in multiple diffs
//
// This function enables composing state changes from different sources,
// which is particularly useful for parallel transaction processing or
// building composite block state transitions.
func MergeStateDiffs(diffs ...*StateDiff) (*StateDiff, error) {
	if len(diffs) == 0 {
		return nil, nil
	}

	accounts := make(map[common.Address]int)                 // Address -> diff index
	storages := make(map[common.Address]map[common.Hash]int) // Address -> Slot -> diff index

	// Check for conflicts
	for diffIndex, diff := range diffs {
		if diff.IsEmpty() {
			continue
		}

		// Check updates for conflicts
		for _, update := range diff.Changes {
			addr := update.Address

			// Conflict: Nonce or Code updated multiple times
			if update.NewNonce > 0 || len(update.NewCode) > 0 {
				if prevIndex, exists := accounts[addr]; exists {
					return nil, NewMergeError(addr, nil, prevIndex, diffIndex, errAccountStateUpdate)
				}
				accounts[addr] = diffIndex
			}

			// Conflict: Storage slot updated multiple times
			if len(update.Storage) > 0 {
				slotMap, exists := storages[addr]
				if !exists {
					slotMap = make(map[common.Hash]int, len(update.Storage))
					for _, kv := range update.Storage {
						slotMap[kv.Key] = diffIndex
					}
					storages[addr] = slotMap
					continue
				}

				for _, kv := range update.Storage {
					// We can allow rewrite slots if we trust accesses
					//if prevIndex, slotExists := slotMap[kv.Key]; slotExists {
					//	return nil, NewMergeError(addr, &kv.Key, prevIndex, diffIndex, errStorageSlotUpdate)
					//}
					slotMap[kv.Key] = diffIndex
				}
			}
		}
	}

	// Merge data
	mergedUpdates := make(map[common.Address]*AccountChange)
	for diffIndex, diff := range diffs {
		if diff.IsEmpty() {
			continue
		}

		for _, update := range diff.Changes {
			addr := update.Address

			existing, exists := mergedUpdates[addr]
			if !exists {
				mergedUpdates[addr] = &AccountChange{
					Address:    addr,
					BalanceInc: uint256.MustFromBig(update.BalanceInc.ToBig()),
					BalanceDec: uint256.MustFromBig(update.BalanceDec.ToBig()),
					NewNonce:   update.NewNonce,
					NewCode:    slices.Clone(update.NewCode),
					Storage:    slices.Clone(update.Storage),
				}
				continue
			}

			if update.NewNonce > 0 {
				existing.NewNonce = update.NewNonce
			}
			if len(update.NewCode) > 0 {
				existing.NewCode = slices.Clone(update.NewCode)
			}
			existing.Storage = slices.Concat(existing.Storage, update.Storage)

			balanceDiff := new(big.Int).Add(update.BalanceDiff(), existing.BalanceDiff())
			existing.BalanceInc, existing.BalanceDec = nil, nil
			if sign := balanceDiff.Sign(); sign != 0 {
				var overflow bool
				if sign > 0 {
					existing.BalanceInc, overflow = uint256.FromBig(balanceDiff)
				} else {
					existing.BalanceDec, overflow = uint256.FromBig(new(big.Int).Abs(balanceDiff))
				}
				if overflow {
					return nil, NewMergeError(addr, nil, 0, diffIndex, errAccountBalanceOverflow)
				}
			}
		}
	}

	var result StateDiff

	if l := len(mergedUpdates); l > 0 {
		result.Changes = make([]*AccountChange, 0, l)
	}
	for _, update := range mergedUpdates {
		result.Changes = append(result.Changes, update)
	}

	if result.IsEmpty() {
		return nil, nil
	}

	return &result, nil
}
