package types

import (
	"encoding/binary"
	"sync"
	"sync/atomic"

	"github.com/ethereum/go-ethereum/common"
	"github.com/holiman/uint256"
	"golang.org/x/crypto/sha3"
)

type toolIDMarshaling struct {
	ID common.Hash `json:"ID"` // adds call to ID() in MarshalJSON
}

//go:generate go run ../../rlp/rlpgen -type SubSlot -decoder=true -out gen_sub_slot_rlp.go
//go:generate go run github.com/fjl/gencodec -type SubSlot -field-override toolIDMarshaling -out gen_sub_slot_json.go

//go:generate go run ../../rlp/rlpgen -type Commitment -decoder=true -out gen_commitment_rlp.go
//go:generate go run github.com/fjl/gencodec -type Commitment -field-override toolIDMarshaling -out gen_commitment_json.go

// SubSlot represents a collection of transactions within a block that have been
// agreed upon by the network validators. Each block can contain multiple SubSlots,
// each with its own set of transactions and state changes.
type SubSlot struct {
	// ID is the unique identifier hash of this SubSlot
	id atomic.Pointer[common.Hash]
	// Txs contains hashes of all transactions included in this SubSlot
	Txs []common.Hash `json:"txs"`

	// Block is the block number this SubSlot belongs to
	Block       uint64      `json:"block"` // Deprecated
	BlockParent common.Hash `json:"blockParent"`
	BlockTime   uint64      `json:"blockTime"`

	// SubSlot is the index of this SubSlot within the block
	Index uint8 `json:"index"`

	// GasUsed tracks the total gas consumed by all transactions in this SubSlot
	GasUsed uint64 `json:"gasUsed" rlp:"-"`
	// Accesses tracks all addresses and storage slots accessed or modified by transactions
	Accesses Accesses `json:"-" rlp:"-"`
	// StateDiff contains all state changes resulting from executing the transactions
	StateDiff *StateDiff `json:"stateDiff" rlp:"-"`
	// Receipts contains transaction receipts for all executed transactions
	Receipts Receipts `json:"receipts" rlp:"-"`

	// mu protects concurrent access to the txs field
	mu sync.Mutex
	// txs holds the actual transaction objects corresponding to Txs
	txs Transactions
}

func NewSubSlot(parentBlock common.Hash, index uint8, blockTime uint64, txs ...common.Hash) *SubSlot {
	return &SubSlot{BlockParent: parentBlock, Index: index, BlockTime: blockTime, Txs: txs}
}

func (ss *SubSlot) ID() common.Hash {
	if id := ss.id.Load(); id != nil {
		return *id
	}
	id, err := calcID(ss.Txs, ss.BlockParent, ss.Index, ss.Index, uint32(ss.BlockTime))
	if err != nil {
		panic(err)
	}
	ss.id.Store(&id)
	return id
}

// IsResolved checks if all transaction hashes in the SubSlot have corresponding
// transaction objects available in the txs field.
func (ss *SubSlot) IsResolved() bool {
	return ss.GetTxs().Len() == len(ss.Txs)
}

// GetTxs returns the transactions in this SubSlot in a thread-safe manner.
func (ss *SubSlot) GetTxs() Transactions {
	ss.mu.Lock()
	defer ss.mu.Unlock()

	return ss.txs
}

// SetTxs attempts to set the transaction objects for this SubSlot.
// Returns false if the number of transactions doesn't match the number of hashes.
func (ss *SubSlot) SetTxs(txs Transactions) bool {
	if txs.Len() != len(ss.Txs) {
		return false
	}

	for i, hash := range ss.Txs {
		if hash != txs[i].Hash() {
			return false
		}
	}

	ss.mu.Lock()
	defer ss.mu.Unlock()

	ss.txs = txs
	return true
}

// Commitment represents a promise to include specific transactions in a SubSlot.
// It contains the result of executing these transactions: gas used, access list,
// storage changes, and logs.
type Commitment struct {
	// ID is the unique identifier hash of this Commitment
	id atomic.Pointer[common.Hash]
	// Txs contains hashes of all transactions included in this Commitment
	Txs []common.Hash `json:"-"`

	// Block is the block number this Commitment is valid for
	Block       uint64      `json:"block"` // Deprecated
	BlockTime   uint64      `json:"blockTime"`
	BlockParent common.Hash `json:"blockParent"`

	// SubSlot is the SubSlot number this Commitment is valid from
	SubSlot uint8 `json:"subSlot"`
	// ExpiresAtSubSlot is the SubSlot number after which this Commitment expires
	ExpiresAtSubSlot uint8 `json:"expires"`

	Fees *uint256.Int `json:"fees"`

	TxsSize uint64 `json:"txsSize"`
	// GasUsed tracks the total gas consumed by all transactions in this Commitment
	GasUsed uint64 `json:"gasUsed"`
	// MaxGasLimit is the maximum single tx gas limit
	MaxGasLimit uint64 `json:"maxGasLimit"`
	// Accesses tracks all addresses and storage slots accessed or modified by transactions
	Accesses Accesses `json:"accesses"`

	// StateDiff contains all state changes resulting from executing the transactions
	StateDiff *StateDiff `json:"stateDiff" rlp:"optional"`
	// Logs contains all event logs generated by the transactions
	Logs []*Log `json:"logs,omitempty" rlp:"optional"`

	// NewTxs contains new transactions included in this Commitment
	NewTxs Transactions `json:"-" rlp:"optional"`

	// mu protects concurrent access to the txs field
	mu sync.RWMutex
	// txs holds the actual transaction objects corresponding to Txs
	txs Transactions

	// executedTxsCount tracks how many transactions have been executed
	executedTxsCount int
}

func (c *Commitment) CloneWithoutNewTxs() *Commitment {
	return &Commitment{
		Accesses:         c.Accesses,
		StateDiff:        c.StateDiff,
		Logs:             c.Logs,
		executedTxsCount: c.executedTxsCount,
		Txs:              c.Txs,
		Block:            c.Block,
		BlockTime:        c.BlockTime,
		BlockParent:      c.BlockParent,
		SubSlot:          c.SubSlot,
		ExpiresAtSubSlot: c.ExpiresAtSubSlot,
		Fees:             c.Fees,
		TxsSize:          c.TxsSize,
		GasUsed:          c.GasUsed,
		MaxGasLimit:      c.MaxGasLimit,
		NewTxs:           nil,
	}
}

func (c *Commitment) ID() common.Hash {
	if id := c.id.Load(); id != nil {
		return *id
	}
	id, err := calcID(c.Txs, c.BlockParent, c.SubSlot, c.ExpiresAtSubSlot, uint32(c.BlockTime))
	if err != nil {
		panic(err)
	}
	c.id.Store(&id)
	return id
}

// ExecutedTxsCount returns the number of transactions that have been executed
// in this Commitment.
func (c *Commitment) ExecutedTxsCount() int {
	return c.executedTxsCount
}

// SetExecutedTxsCount sets the count of executed transactions in this Commitment.
func (c *Commitment) SetExecutedTxsCount(executedTxsCount int) {
	c.executedTxsCount = executedTxsCount
}

// IsResolved checks if all transaction hashes in the Commitment have corresponding
// transaction objects available in the txs field.
func (c *Commitment) IsResolved() bool {
	return c.GetTxs().Len() == len(c.Txs)
}

// GetTxs returns the transactions in this Commitment in a thread-safe manner.
func (c *Commitment) GetTxs() Transactions {
	c.mu.RLock()
	defer c.mu.RUnlock()

	return c.txs
}

// SetTxs attempts to set the transaction objects for this Commitment.
// Returns false if the number of transactions doesn't match the number of hashes.
func (c *Commitment) SetTxs(txs Transactions) bool {
	if txs.Len() != len(c.Txs) {
		return false
	}

	c.mu.Lock()
	defer c.mu.Unlock()

	c.txs = txs
	return true
}

// Bundle is a request to create a new Commitment, combining new transactions
// with existing Commitments. It allows for modular composition of transactions
// and their effects.
type Bundle struct {
	// BasedCommitments contains hashes of existing Commitments this Bundle builds upon
	BasedCommitments []common.Hash `json:"based"`

	// Block is the target block number for this Bundle
	Block       uint64      `json:"block"` // Deprecated
	BlockParent common.Hash `json:"blockParent"`

	// SubSlot is the target SubSlot number for this Bundle
	SubSlot uint8 `json:"subSlot"`
	// ExpiresAtSubSlot is the SubSlot number after which this Bundle expires
	ExpiresAtSubSlot uint8 `json:"expires"`
	// NewTxs contains new transactions to be included in the resulting Commitment
	NewTxs Transactions `json:"newTxs"`

	// executingTxs contains transactions to be re-executed in case of conflicts,
	// combining new transactions and transactions from conflicting Commitments
	executingTxs Transactions

	// The following fields store aggregated data derived from base Commitments

	// basedTxs stores transaction hashes from all base Commitments
	basedTxs []common.Hash
	// basedLogs stores event logs from all base Commitments
	basedLogs []*Log
	// basedTxsSize
	basedTxsSize uint64
	// basedGasUsed stores accumulated gas usage from all base Commitments
	basedGasUsed uint64
	// basedMaxGasLimit stores maximum single gas limit of all base Commitments
	basedMaxGasLimit uint64
	// basedAccesses stores merged access lists from all base Commitments
	basedAccesses Accesses
	// basedStateDiff stores merged state changes from all base Commitments
	basedStateDiff *StateDiff
}

// ExecutingTxs returns transactions that need to be executed when creating a Commitment
// from this Bundle, including re-executed transactions from conflicting Commitments.
func (b *Bundle) ExecutingTxs() Transactions {
	return b.executingTxs
}

// SetExecutingTxs sets the transactions that need to be executed when creating a
// Commitment from this Bundle.
func (b *Bundle) SetExecutingTxs(executingTxs Transactions) {
	b.executingTxs = executingTxs
}

// BasedLogs returns event logs aggregated from base Commitments.
func (b *Bundle) BasedLogs() []*Log {
	return b.basedLogs
}

// SetBasedLogs sets the aggregated event logs from base Commitments.
func (b *Bundle) SetBasedLogs(basedLogs []*Log) {
	b.basedLogs = basedLogs
}

// BasedTxsSize returns the total size of transactions from all base Commitments.
func (b *Bundle) BasedTxsSize() uint64 {
	return b.basedTxsSize
}

// SetBasedTxsSize sets the total size of transactions from all base Commitments.
func (b *Bundle) SetBasedTxsSize(txsSize uint64) {
	b.basedTxsSize = txsSize
}

// BasedGasUsed returns the total gas used by all base Commitments.
func (b *Bundle) BasedGasUsed() uint64 {
	return b.basedGasUsed
}

// SetBasedGasUsed sets the total gas used by all base Commitments.
func (b *Bundle) SetBasedGasUsed(gasUsed uint64) {
	b.basedGasUsed = gasUsed
}

func (b *Bundle) BasedMaxGasLimit() uint64 {
	return b.basedMaxGasLimit
}

func (b *Bundle) SetBasedMaxGasLimit(maxGasLimit uint64) {
	b.basedMaxGasLimit = maxGasLimit
}

// BasedTxs returns transaction hashes from all base Commitments.
func (b *Bundle) BasedTxs() []common.Hash {
	return b.basedTxs
}

// SetBasedTxs sets the transaction hashes from all base Commitments.
func (b *Bundle) SetBasedTxs(basedOnTxs []common.Hash) {
	b.basedTxs = basedOnTxs
}

// BasedAccesses returns the merged access lists from all base Commitments.
func (b *Bundle) BasedAccesses() Accesses {
	return b.basedAccesses
}

// SetBasedAccesses sets the merged access lists from all base Commitments.
func (b *Bundle) SetBasedAccesses(accessList Accesses) {
	b.basedAccesses = accessList
}

// BasedStateDiff returns the merged state changes from all base Commitments.
func (b *Bundle) BasedStateDiff() *StateDiff {
	return b.basedStateDiff
}

// SetBasedStateDiff sets the merged state changes from all base Commitments.
func (b *Bundle) SetBasedStateDiff(stateDiff *StateDiff) {
	b.basedStateDiff = stateDiff
}

func calcID(txs []common.Hash, parent common.Hash, subSlot, expires byte, blockTime uint32) (common.Hash, error) {
	hasher := sha3.NewLegacyKeccak256()

	for _, hash := range txs {
		_, err := hasher.Write(hash.Bytes())
		if err != nil {
			return common.Hash{}, err
		}
	}

	if _, err := hasher.Write(parent.Bytes()); err != nil {
		return common.Hash{}, err
	}

	if _, err := hasher.Write([]byte{subSlot}); err != nil {
		return common.Hash{}, err
	}

	if _, err := hasher.Write([]byte{expires}); err != nil {
		return common.Hash{}, err
	}

	blockTimeBytes := make([]byte, 4)
	binary.BigEndian.PutUint32(blockTimeBytes, blockTime)
	if _, err := hasher.Write(blockTimeBytes); err != nil {
		return common.Hash{}, err
	}

	return common.BytesToHash(hasher.Sum(nil)), nil
}
